### ISSUE TITLE
Example get_current_weather

### ISSUE THREAD

**Issue by AdrienLemaire** [fj0r/ai.nu#2]
Hi @fj0r and thanks for this great plugin which I'm starting to discover.

Can you give us an example for querying the function get_current_weather ?

Here's what I understand it should look like
```console
> ai-do somePrompt --function [get_current_weather --location "San Francisco, US"]
```

There doesn't seem to be a prompt available that is adapted to this function, I'm getting the error `Cannot find column 'tool_calls'` when trying existing prompts.

**Comment by orbsh** [comment]
```nushell
"Choose a function call: Will it rain tomorrow? I'm in San Francisco."
| ai-do general en -f [get_current_weather] -m <model support fuction call>
| to yaml
```
Results:
```yaml
- id: call_20250108110159e36662a911f84245_0
  index: 0
  type: function
  function:
    name: get_current_weather
    arguments: '{"location": "San Francisco, CA", "unit": "fahrenheit"}'
```
- If you're unsure what prompt to use, you can use `general`.
- In edit mode, you can execute `ai-editor-run` incrementally in the editor (For example, execute `:terminal` in Vim).
- The `-f` parameter is a list of callable functions. Based on your message, the LLM will choose one to call and provide the appropriate parameters.
- In this example, even without the `Choose a function call: ` prompt, it might still successfully call the function and output both the message and `tool_calls` (in most cases, only `tool_calls` are needed).
- Use `ai-config-upsert-function` to add your own functions.

I will add this content to the README.
