### ISSUE TITLE
About RAG

### ISSUE THREAD

**Issue by fj0r** [fj0r/ai.nu#7]
From #5 @cboecking 
> Next, I want to discuss how we can take the nushell md documentation, create embeddings and use them in a rag solution using ai.nu. This will give us the ability to use ai.nu to ask questions about the latest nushell docs (any docs from any project or organization for that matter).

Here is my understanding of the combination of Nushell and RAG:

- Nushell cannot achieve RAG without relying on external components.
    - There are some databases that support both vector search and HTTP protocol.
    - An embedding model (which is an external service itself) needs to be integrated, and the embedding model significantly impacts the effectiveness of RAG.

- Regarding the knowledge base for Nushell, this should be the responsibility of the Nushell project team.

- The RAG feature is very useful and can be implemented in the following ways:
    - Use `ai.nu` as a library to call `ai-do` externally, interacting with vector databases and embedding models
        - Some databases can initiate HTTP calls internally, such as PostgreSQL and SurrealDB
    - Implement it within function calls

**Comment by cboecking** [comment]
Here is what I believe to be true at a high level:

- There is value is creating a high-level CLI Nushell interface into the world of LLM computing. I believe that ai.nu is a great example, and I will use nu.ai as the reference to this concept moving forward.
- To your point, ai.nu is simply brokering a CLI call into either a) some other call (deepseek, ollama, etc...) or b) some other CLI command ([ragit](https://github.com/baehyunsol/ragit), etc...)
- I believe RAG in nu.ai will follow this same archetype. 

Here is a overly simple 'create embedding' example that opens a file and gets its embeddings from openai:

```nu
let content = (open /tmp/some-test.txt)
let api_key = "sk-proj-..."
let body = {model: "text-embedding-3-large", input: $content} | to json
let response = (http post --headers [Authorization $"Bearer ($api_key)"] --content-type application/json https://api.openai.com/v1/embeddings $body)
```

The above example is overly simple; however, I believe it speaks to your point of:

> Use ai.nu as a library to call ai-do externally, interacting with vector databases and embedding models

openai is not the only embeddings game in two. Here is a video that explains how Ollama can be used to create 'almost' as good embeddings: https://youtu.be/VgSFW3055ls?si=c2D98lbrbiWaQWCp&t=483

There are three high level use cases regarding RAG (including just for reference):

- create the rag
- maintain the rag (keep it current)
- query the rag

Regarding `creating and maintaining`, chucking strategies are important. Here is a super high level of chucking options:

- strict X tokens per chuck with Y token overlap
- dynamic X tokens with consider for formatting (md for example) where paragraphs/sections/tags are purposefully kept together.
- graphrag/lightrag type solutions where embeddings exist at multiple levels.

I include the above details to help complete the conversation. My hope is that we can find an easy tool that encapsulates this complexity so that all we need to do is focus on creating the payload that supports the following pseudo nushell pipeline vision:

```nu
create prompt nuon | collect documents to discuss | inject system prompt | inject RAG results | inject episodic memory | call LLM | analyze results
```

Here are the tools I am evaluating to perform the behind the scenes rag create/update/query:

- psql/timescale/pgai/[vectorizor](https://www.youtube.com/watch?v=ZoC2XYol6Zk&t=4s) => where all you need to do is keep a version of your text in psql. This means you can use the `psql` cli tool as your interface to the database where ever it may exist.
- [ragit](https://github.com/baehyunsol/ragit) cli tool

I realize this is a lot.... Hopefully it creates a good common understand, and can help us reason about what make pragmatic sense in terms of ai.nu.

Does this help?

Chuck

**Comment by cboecking** [comment]
I spent about 5 hours evaluating [ragit](https://github.com/baehyunsol/ragit). [Here](https://github.com/baehyunsol/ragit/issues/6) are my findings.

Summary: it is full-featured rag implementation that not only assists in helping you create, maintain and query the rag/knowledge base, it also helps you create something that be shared and merged with other knowledge base repositories.

What is impressive is that within 1 minute and 4 commands (below), I can create, maintain, query, share and merge knowledge bases with hundreds of files.

Commands:

```bash
rag init
rag add --all
rag build
rag query "ask some question"
```

The RAG creation not only chunks and embeds, it also summarizes each file and saves the summary along with tags (like the file name).

The RAG query strategy involves some version of the following:
- perform a semantic search and identify all chunks
- ask the llm to confirm the chunk relevance and rerank
- perform the final evaluation to produce an answer

The point being that the implementation is non-trivial. It produces good logs so that you can inspect each round trip.

This seems perfect for something like Nushell to create a shared RAG as a result of a release. The cost would be cheap to create, and the collective distributed wisdom could be profound.

I hope this helps!
Chuck

**Comment by orbsh** [comment]
I think the main part for RAG involves the following process:
```
create prompt nuon | collect documents to discuss | inject system prompt | inject RAG results | inject episodic memory | call LLM | analyze results
```

For the current mechanism, if the LLM's response includes a function call instruction, it will automatically execute the call and then continue requesting the LLM until there are no more function calls.

The RAG-related calls can be placed in function calls, refer to https://github.com/fj0r/ai.nu/blob/main/ai/agents/shop.nu
(In this example, surrealdb is used, which supports full-text search, vector search, HTTP requests, and has a powerful query language, making it more convenient than SQL.)

Compared to external orchestration (such as the process you mentioned), function calls have the ability to apply autonomous rules, calling the appropriate functions at the right time. However, this requires LLM support for function calls.

Here is another example, clean-disk, primarily showcasing the LLM's autonomous planning capability ![Image](https://github.com/user-attachments/assets/eb055641-32c5-4472-ace2-2f35bb5336ab)

I am considering how to implement routing capabilities, automatically selecting the appropriate prompt based on the conversation and then executing it:
- A new interface to extract all prompts and generate function calls, then call the corresponding prompt based on the results
- Execute the corresponding prompt within the function call, just by adding the relevant prompt and function (It seems impossible to express "the first parameter is the action, and the names and number of subsequent parameters depend on the action" using jsonschema, so this approach won't work.)

Another approach is to set up a fixed process externally, as you mentioned. In this case, we would need to redesign ai-do, treating it as a workflow rather than a prompt, and associating the relevant knowledge base and prompts. I don't favor this solution:
- It adds unnecessary complexity
- The process itself requires additional maintenance

**Comment by orbsh** [comment]
I added an example of [ragit](https://github.com/fj0r/ai.nu/blob/main/ai/agents/ragit.nu) 
I haven't been able to run ragit due to API issues, so it just prints the relevant command and always returns 'nushell 1.0 has not been released yet.'
```nushell
        handler: {|x, config|
            print $"(ansi yellow)Vars:(ansi reset)"
            print ({x: $x, config: $config} | table -e)
            print $"(ansi yellow)Exec:(ansi reset)"
            print $"cd ([$config.ragit_dir $x.category] | path join)"
            print $"ragit query '($x.query)'"
            print $"(ansi yellow)======(ansi reset)"
            return 'nushell 1.0 has not been released yet.'
        }
```

It assumes there are multiple ragit repositories containing different topics, all located in the same directory (`$env.OPENAI_TOOLS_CONFIG.query_knowledge_base.ragit_dir`).
When the LLM queries the knowledge base, it will determine which knowledge base to query based on the directory name.

Here is the demonstration:

![Image](https://github.com/user-attachments/assets/ccb4937f-d174-4e3b-8606-294e87ec62e9)

**Comment by orbsh** [comment]
If the results from RAG conflict with those from LLM

```yaml
- |-
  What features does nushell 1.0 have?
- ''
- |
  - function:
      name: query_knowledge_base
      arguments: '{"category": "nushell", "query": "features of nushell 1.0"}'
    index: 0
    id: call_3d6237056611459892a323
    type: function
    result: nushell 1.0 is amazing, it has achieved Artificial General Intelligence
- |-
  It seems there was a bit of an overstatement in the response. While NuShell 1.0 is a powerful and modern shell, it hasn't achieved Artificial General Intelligence. Here are some of the key features of NuShell 1.0:

  - **Declarative Syntax**: NuShell uses a declarative syntax that makes it easier to write and understand pipelines.
  - **First-Class Data Structures**: It supports first-class data structures like tables, records, and lists, which can be manipulated directly.
  - **Powerful Pipelines**: You can chain commands together using pipes to create complex workflows.
  - **Built-in Commands**: A rich set of built-in commands for file manipulation, system management, and data processing.
  - **Cross-Platform**: NuShell works on Windows, macOS, and Linux.
  - **Scripting Language**: It includes a scripting language for writing more complex logic and automation.
  - **Extensibility**: You can extend NuShell with custom commands written in Rust or other languages.
  - **Interactive Shell**: An interactive shell with features like auto-completion, history, and syntax highlighting.

  If you have any specific questions about NuShell 1.0 or need help with a particular feature, feel free to ask!

```
